config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index" 

  devise_for :users
  resources :public_recipes, only: [:index]
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :new, :create, :destroy, :show] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end

  get '/toogle/:id', to: 'recipes#toogle'
  get '/general_shopping_list', to: 'shopping_list#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    # Define abilities for the user here. For example:
    #
    return unless current_user.present?

    can :manage, Recipe, user: current_user
    can :manage, Food, user: current_user

    can :read, Recipe, public: true

    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :recoverable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?

  has_many :foods
  has_many :recipes

  validates :name, presence: true

  private

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    exception.default_message = 'You are not authorized to perform this task'
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to root_path, alert: exception.message }
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  def index
    @foods = Food.where(user: current_user)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      flash[:notice] = 'Food is created!'
      redirect_to foods_path
    else
      flash[:alert] = 'Food is not created!'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:notice] = 'Food has been deleted.'
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).includes(:user).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_foods = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_parms)
    @recipe_food.recipe_id = params[:recipe_id]

    @existing_recipe_food = RecipeFood.where(recipe_id: params[:recipe_id], food_id: @recipe_food.food_id)

    if @existing_recipe_food.exists?
      @existing_recipe_food.first.quantity = @recipe_food.quantity
      if @existing_recipe_food.first.save
        flash[:notice] = 'Ingredient has been added'
        redirect_to "/recipes/#{params[:recipe_id]}"
      else
        flash[:error] = 'An error has occured'
        render :new, status: 422
      end
    elsif @recipe_food.save
      flash[:notice] = 'Ingredient has been added'
      redirect_to "/recipes/#{params[:recipe_id]}"
    else
      flash[:error] = 'An error has occured'
      render :new, status: 422
    end
  end

  def destroy
    @recipe = RecipeFood.find_by(food_id: params[:id], recipe_id: params[:recipe_id])
    if @recipe.destroy
      flash[:notice] = 'Ingredient has been removed'
      redirect_to(request.referrer || root_path)
    else
      flash[:error] = 'An error has occured'
    end
  end

  private

  def recipe_food_parms
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @foods = Food.joins(:recipe_foods).where(recipe_foods: { recipe_id: @recipe.id }).includes([:recipe_foods])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :index, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toogle
    @recipe = Recipe.find_by_id(params[:id])
    @recipe.public = !@recipe.public
    if @recipe.save
      redirect_to(request.referrer || root_path)
    else
      flash[:error] = 'Error updating recipe'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    all_public_recipe_foods = Recipe.where(public: true).includes(recipe_foods: [:food]).map(&:recipe_foods)
      .flatten.map(&:food)
    all_user_foods = Food.where(user: current_user)

    @missing_foods = all_public_recipe_foods.reject do |food|
      food.quantity > all_user_foods.select do |user_food|
                        user_food.id == food.id
                      end.first.quantity
    end
    @amt = @missing_foods.length
    @total = @missing_foods.map do |food|
      food.price * food.recipe_foods.select do |recipe|
                     recipe.food_id == food.id
                   end.first.quantity
    end.sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/foods/index.html.erb
<%= render "shared/navbar" %>

<div class="container">
  <%= link_to "Add Food", new_food_path, class: "add-food-btn" %>
</div>

<div class="table-container">
  <table>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Price</th>
      <th>Delete</th>
    </tr>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td>$<%= food.price %></td>
        <td><%= button_to "Delete Food",
          food_path(food),
          method: :delete,
          data: {
            confirm: "Are you sure you want to delete this food?"
          },
          class: "delete-button" %></td>

      </tr>

    <% end %>
  </table>
</div>

app/views/foods/new.html.erb
<%= render "shared/navbar" %>

<div class="new-food-container">
  <div class="small-food-container">

    <h1 class="food-heading">Create Food</h1>
    <div class="text-fields-container">
      <div>
        <%= form_with model: @food do |f| %>
          <%= f.text_field :name,
                       placeholder: "Enter Food Name",
                       class: "px-2 py-4 my-4",
                       required: true %>

          <div>
            <%= f.text_field :measurement_unit,
                         placeholder: "Enter Measurement Unit (e.g., kg)",
                         class: "px-2 py-4 my-4",
                         required: true %>
          </div>

          <div>
            <%= f.number_field :price,
                           step: "0.01",
                           placeholder: "Enter Food Price",
                           class: "px-2 py-4 my-4",
                           required: true %>
          </div>

          <div>
            <%= f.number_field :quantity,
                           step: "1",
                           placeholder: "Enter Food Quantity",
                           class: "px-2 py-4 my-4",
                           required: true %>
          </div>

          <div class="text-white">
            <%= f.submit class: "cursor-pointer" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<%= content_tag(:header, class: "header_bg") do %>
  <%= render "shared/navbar" %>
<% end %>
<div class="flex place-content-center my-10">
  <p class="text-6xl welcome-page">Welcome,
    <%= "#{current_user.name}" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'logo_image.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://kit.fontawesome.com/5d26ebde18.js" crossorigin="anonymous"></script>

  </body>
</html>

app/views/public_recipes/index.html.erb
<%= render "shared/navbar" %>

<div class="public-recipe-container">
  <% @public_recipes.each do |recipe| %>
    <div class="public-recipe-item">
      <div class="public-recipe-names">
        <h2 class="text-xl">
          <%= link_to recipe.name,
          recipe,
          class: "font-medium text-blue-600 dark:text-blue-500  hover:underline" %></h2>
        <br/>
        <i>By</i>
        <%= recipe.user.name %>
      </div>
      <div class="public-recipe-item-total">
        Total Food Items:
        <%= recipe.recipe_foods.count %>
        <br/>
        <br/>
        <% recipe_total_price = 0 %>
        <% recipe.recipe_foods.each do |recipe_foods_item| %>
          <% recipe_total_price += recipe_foods_item.quantity * recipe_foods_item.food.price %>

        <% end %>
        Total Price: $<%= recipe_total_price %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipe_foods/create.html.erb
<div>
  <h1 class="font-bold text-4xl">RecipeFoods#create</h1>
  <p>Find me in app/views/recipe_foods/create.html.erb</p>
</div>

app/views/recipe_foods/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">RecipeFoods#destroy</h1>
  <p>Find me in app/views/recipe_foods/destroy.html.erb</p>
</div>

app/views/recipe_foods/new.html.erb
<%= render "shared/navbar" %>
<div class="flex flex-col items-center">
  <div class="">
    <h1 class="text-6xl my-4 w-96">Add Ingredients for Recipe</h1>
    <%= form_with url: "/recipes/#{params[:recipe_id]}/recipe_foods", model: @recipe_foods, method: :post do |form| %>
      <div class="my-4 w-full flex flex-row justify-between items-center">
        <%= form.label :quantity, class: "min-w-20" %>
        <div class="flex items-start ms-2 w-full">
          <%= form.number_field :quantity, required: true %>
        </div>
      </div>
      <div class="my-4 w-full flex flex-row justify-between items-center">
        <%= form.label :food_id, {}, { class: "min-w-20" } %>
        <div class="flex items-start ms-2 w-full">
          <%= form.select :food_id,
                      options_for_select(Food.all.map { |f| [f.name, f.id] }),
                      {},
                      {
                        class:
                          "bg-gray-50 border border-gray-700 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                      } %>
        </div>
      </div>
      <div class="my-4 w-full">
        <%= form.submit "Add Ingredients",
                    class:
                      "bg-black text-white py-2 px-4 rounded-sm w-full cursor-pointer border-2 hover:bg-white hover:text-black hover:border-black transition" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %>
        prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-2">
    <%= form.label :name %><br>
    <%= form.text_field :name, autofocus: true, required: true, class: "w-full" %>
    <% recipe.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field my-2">
    <%= form.label :description %><br>
    <%= form.text_area :description, required: true, rows: 5, cols: 23, class: "w-full" %><br>
    <% recipe.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field my-2">
    <%= form.label :preparation_time %><br>
    <%= form.text_field :preparation_time,
                    required: true,
                    class: "w-full" %>
    <% recipe.errors.full_messages_for(:preparation_time).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field my-2">
    <%= form.label :cooking_time %><br>
    <%= form.text_field :cooking_time, required: true, class: "w-full" %>
    <% recipe.errors.full_messages_for(:cooking_time).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class:
                  "bg-black text-white py-2 px-4 rounded-sm w-full my-2 cursor-pointer border-2 hover:bg-white hover:text-black hover:border-black transition" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
</div>

app/views/recipes/index.html.erb
<%= render "shared/navbar" %>

<div class="flex flex-col items-center">
  <h1 class="text-6xl my-4">Recipes</h1>

  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <div
        class="
          flex
          flex-col
          p-4
          border-solid
          border-2
          border-black
          items-center
          my-4
        "
      >
        <div class="flex flex-row">
          <p class="text-4xl me-2">
            <%= link_to recipe.name,
            recipe,
            class: "font-medium text-blue-600 dark:text-blue-500  hover:underline" %>
          </p>
          <p class="text-base ms-2 w-60"><%= recipe.description %></p>
        </div>
        <div class=" flex self-start ">
          <%= button_to "Remove",
          recipe_path(recipe),
          method: :delete,
          class: "font-medium text-blue-600 dark:text-blue-500  hover:underline" %>
        </div>
      </div>
      <p>
      </p>
    <% end %>
  </div>

  <%= link_to "New recipe",
  new_recipe_path,
  class: "font-medium text-blue-600 dark:text-blue-500  hover:underline" %>

</div>

app/views/recipes/new.html.erb
<%= render "shared/navbar" %>

<div class="flex flex-col items-center">
  <div class="">
    <h1 class="text-6xl my-4">New recipe</h1>

    <%= render "form", recipe: @recipe %>
  </div>
</div>

app/views/recipes/show.html.erb
<%= render "shared/navbar" %>

<div class="flex flex-col items-center">
  <h1 class="text-6xl my-4"><%= @recipe.name %></h1>
  <div class="flex flex-col items-start w-3/4">
    <div class="flex flex-row my-6 justify-between">
      <div class="flex flex-col me-6">
        <p class="text-lg mx-2 my-4 w-96"><strong>Preparation time:
          </strong><%= @recipe.preparation_time %></p>
        <p class="text-lg mx-2 my-4 w-96"><strong>Cooking time:
          </strong><%= @recipe.cooking_time %></p>
        <p class="text-lg mx-2 my-4 w-96"><%= @recipe.description %></p>
      </div>
      <% if @recipe.user === current_user %>
        <div class="flex flex-row ms-6">
          <span class="me-2 my-4"><strong>Public
            </strong></span>
          <div class="my-3">
            <%= link_to "/toogle/#{@recipe.id}" do %>
              <% if @recipe.public %>
                <i class="fas fa-toggle-on fa-2x text-green-400"></i>
              <% else %>
                <i class="fas fa-toggle-off fa-2x text-red-400"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="flex flex-row w-1/2">
      <%= link_to "Generate shopping list",
      "/general_shopping_list",
      class:
        "mx-2 bg-black text-white py-2 px-4 rounded-sm w-full cursor-pointer border-2 hover:bg-white hover:text-black hover:border-black transition w-fit" %>
      <% if @recipe.user === current_user %>
        <%= link_to "Add ingredients",
        new_recipe_recipe_food_path(@recipe),
        class:
          "mx-2 bg-black text-white py-2 px-4 rounded-sm w-full cursor-pointer border-2 hover:bg-white hover:text-black hover:border-black transition w-fit" %>
      <% end %>

    </div>

    <div class="relative overflow-x-auto w-full my-6 mx-2">
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead
          class="
            text-base
            text-gray-700
            uppercase
            bg-gray-50
            dark:bg-gray-700
            dark:text-gray-400
            bg-white
            border-b
          "
        >
          <tr>
            <th scope="col" class="px-6 py-3">
              Food
            </th>
            <th scope="col" class="px-6 py-3">
              Quantity
            </th>
            <th scope="col" class="px-6 py-3">
              Price
            </th>
            <% if current_user.id == @recipe.user.id %>
              <th scope="col" class="px-6 py-3">Actions</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @foods.each_with_index do |food, index| %>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <th
                scope="row"
                class="
                  px-6
                  py-4
                  font-medium
                  whitespace-nowrap
                  text-white
                  dark:text-gray-900
                "
              >
                <p><%= "#{food.name}" %></p>
              </th>
              <td class="px-6 py-4 text-black">
                <%= food.recipe_foods.select { |recipe| recipe.food_id == food.id }.first.quantity %>
                <%= food.measurement_unit %>
              </td>
              <td class="px-6 py-4 text-black">
                $<%= food.price *
                  food.recipe_foods.select { |recipe| recipe.food_id == food.id }.first.quantity %>
              </td>
              <% if current_user.id == @recipe.user.id %>
                <td class="px-6 py-4">
                  <%= button_to "Remove",
                  recipe_recipe_food_path(@recipe.id, food.id),
                  method: :delete,
                  class: "text-red-600 underline hover:pointer-cursor" %>
                </td>
              <% end %>

            </tr>
          <% end %>

        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <h1 class="logo">
      <%= link_to "Recipe App", root_path %>
    </h1>
    <ul>
      <li><%= link_to "Foods",
        foods_path,
        class: class_names("text-gray-50", { active: current_page?(foods_path) }) %></li>
      <li><%= link_to "Recipes",
        recipes_path,
        class: class_names("text-gray-50", { active: current_page?(recipes_path) }) %></li>

      <li><%= link_to "Public Recipes",
        public_recipes_path,
        class:
          class_names("text-gray-50", { active: current_page?(public_recipes_path) }) %></li>
      <li><%= link_to "Shopping List",
        general_shopping_list_path,
        class:
          class_names("text-gray-50", { active: current_page?(general_shopping_list_path) }) %></li>
      <li><%= button_to "Sign Out",
        destroy_user_session_path,
        method: :delete,
        class: "logout-btn" %></li>
    </ul>
  </nav>
</header>

app/views/shopping_list/index.html.erb
<%= render "shared/navbar" %>

<div class="flex flex-col items-center">
  <h1 class="font-bold text-4xl my-4">ShoppingList</h1>
  <div class="flex flex-row justify-between w-1/2">
    <p>Amount of food items to buy:
      <%= @amt %></p>
    <p>Total price: $<%= @total %></p>
  </div>
  <div class="flex flex-col items-start w-3/4">

    <div class="relative overflow-x-auto w-full my-6 mx-2">
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead
          class="
            text-base
            text-gray-700
            uppercase
            bg-gray-50
            dark:bg-gray-700
            dark:text-gray-400
            bg-white
            border-b
          "
        >
          <tr>
            <th scope="col" class="px-6 py-3">
              Food
            </th>
            <th scope="col" class="px-6 py-3">
              Quantity
            </th>
            <th scope="col" class="px-6 py-3">
              Price
            </th>
          </tr>
        </thead>
        <tbody>
          <% @missing_foods.each_with_index do | food, index| %>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <th
                scope="row"
                class="
                  px-6
                  py-4
                  font-medium
                  whitespace-nowrap
                  text-white
                  dark:text-gray-900
                "
              >
                <p><%= "#{food.name}" %></p>
              </th>
              <td class="px-6 py-4 text-black">
                <%= food.recipe_foods.select { |recipe| recipe.food_id == food.id }.first.quantity %>
                <%= food.measurement_unit %>
              </td>
              <td class="px-6 py-4 text-black">
                $<%= food.price *
                  food.recipe_foods.select { |recipe| recipe.food_id == food.id }.first.quantity %>
              </td>

            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>